# docker-compose --file postgres-docker-compose.yml up
version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "usuario"
      POSTGRES_PASSWORD: "usuario"
      POSTGRES_DB: "sistemadeponto"
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    ports:
       - 5432:5432
volumes:
  db_volume: